version: "3.9"
   
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=polls
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=polls
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
